import Head from 'next/head'
import Image from 'next/image'
import Carousel from '../components/Carousel'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Regine Agency</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.home}>
        <Carousel/>
      </div>
    </>
  )
}
